### ISSUE TITLE
format of room_camera.txt

### ISSUE THREAD

**Issue by zhz218** [yindaz/pbrs#1]
Hi,

can you give some information about the file format for the ```room_camera.txt``` files?

Thanks!

**Comment by yindaz** [comment]
Each line represents one camera, in the order of the index, with the format:
[center x, center y, center z, forward x, forward y, forward z, up x, up y, up z, fov x, fov y, camera quality]

In other words, each line gives you the camera center coordinate, then the direction that the camera is looking at, followed by the up direction of the camera, and the field of view of x and y direction respectively. The last digit is a measurement of how likely the camera is as a scene looking camera. It is not a camera parameter and you may ignore it. Basically, the first 9 digits tells you the camera extrinsic matrix. The 10, 11th digits, together with the image size, tells you the camera intrinsic matrix.
