### ISSUE TITLE
Replacing environment light with directional light

### ISSUE THREAD

**Issue by GH-HOME** [yindaz/pbrs#10]
Hi, I try to render a scene with directional light. However, using mlt integrator, the rendering results have many noisy points under certain light directions, as the figure I show below.
![mlt_camera_0_light_0 372_0 628_-0 683](https://user-images.githubusercontent.com/18206839/52030145-ce999700-2559-11e9-8ab3-7ab5c5ed5769.png)
The mitsuba log shows "Encountered a path that could *never* be mutated!".

 I also try 'direct' and 'pssmlt' integrator to rendering the scene. However, only black images output.

The aim is just rendering the scene with directional light with mitsuba. could you please provide some suggestions regarding that?

**Comment by yindaz** [comment]
Rendering indoor environment can be challenging due to inter-reflections caused by complex structures. You may try more conservative rendering integrator with super large sample rate.
