### ISSUE TITLE
Link to dataset is broken

### ISSUE THREAD

**Issue by MichaelRamamonjisoa** [yindaz/pbrs#11]
Hi, 

Thank you for your work.
The link to the PBRS project seems to be broken now.

**Comment by pemo-ml** [comment]
Hi yindaz,
the download link originally found on the wesbite for LDR renderings is also unavailable.
Will the dataset be made available again?

Thank you in advance!

**Comment by 94929** [comment]
Hi,

Same issue for the [precomputed camera views](http://pbrs.cs.princeton.edu/pbrs_release/data/camera_v2.zip) :)
I would appreciate if you could let us know if the links will be available in the future.

Thanks!

**Comment by yindaz** [comment]
Thanks for interesting in pre-rendered data. The links are temporarily off upon the request from from SUNCG authors. Please reach out to them for solutions. Sorry for the inconvenience.

**Comment by MichaelRamamonjisoa** [comment]
Thank you for your feedback. SUNCG dataset also seems to be unavailable. It's a bit of a pity since several work has already been published using those datasets. I assume that we should not share copies of previously downloaded data ?

**Comment by yindaz** [comment]
That you need to consult the SUNCG author as well. I've only got their request to put down the links but nothing about specific action on data in the wild.

**Comment by pemo-ml** [comment]
The unavailability of the SUNCG data set is probably related to this issue - https://www.law.com/therecorder/2019/06/06/home-design-site-claims-facebook-princeton-nabbed-data-for-3-d-objects/?slreturn=20190507114932

**Comment by MichaelRamamonjisoa** [comment]
Another link on that: https://futurism.com/tech-suing-facebook-princeton-data

Let's hope we will soon be given details on the (un)availability of the data...
