### ISSUE TITLE
Is it possible to get corresponding voxel?

### ISSUE THREAD

**Issue by sunshineatnoon** [yindaz/pbrs#4]
First, thanks for this awesome repo, I'm using it in my project.

Is it possible to get the semantic volumetric ground truth as [sscnet](https://github.com/shurans/sscnet)? I found there's no correspondences between these two projects (i.e. for the rendered image here, I can't find its corresponding volume).

Thanks for your help.

**Comment by yindaz** [comment]
Yes, this is an independent project, and there would be very litter correspondence with sscnet. Also this project focuses on the 2D rendering of the 3D ground truth. Even though, I think it is still possible to get the 3D voxel ground truth. Our data uses version 0 of the SUNCG, and the camera coordinates we are using is consistent with SUNCG.

**Comment by sunshineatnoon** [comment]
Thanks for the quick reply. I guess I can use the camera files here to generate voxel in [sscnet](https://github.com/shurans/sscnet). Another question I have is regarding the `fov` parameter of camera. In [Generate camera](https://github.com/yindaz/pbrs#generate-camera) session, the `-xfov` parameter is 0.5534, which corresponds to 31.71 degree, while in [mitsuba_render.py](https://github.com/yindaz/pbrs/blob/master/mitsuba_render.py), the `fov` parameter is set to 63.414, which one is the field of view of the camera?

**Comment by yindaz** [comment]
31.71 is half of the fov on x-axis. So 63.414 is the fov.

**Comment by sunshineatnoon** [comment]
Got it, Thanks!
