### ISSUE TITLE
Assertion error node->parent == this 

### ISSUE THREAD

**Issue by yzp12** [yindaz/pbrs#6]
Hi @yindaz ,
I encountered following error when running the scn2scn binary. Do you have an idea what is going on? Thank you!
GAPS FATAL ERROR.  ABORTING:: No such file or directory                                                                       
Assertion error node->parent == this at line 368 in file R3SceneNode.cpp                                                     
Aborted (core dumped)

**Comment by yindaz** [comment]
The error message means that GAPS cannot find some files as input. Please check scn2scn.cpp for the required input by scn2scn.
