### ISSUE TITLE
about preparing 3D models by using mtsimport

### ISSUE THREAD

**Issue by dyanmei** [yindaz/pbrs#8]
Hi, I am trying to prepare 3D models by using mtsimport.
I found that the code you provided contains mitsuba, but does it contain the code of collada?  I was failed to build mtsimport from the downloaded .deb files.

**Comment by yindaz** [comment]
My code should work well with the standard/public version of the Mitsuba. If you have any trouble compiling Mitsuba standard version, please see their Q&A. Thanks.

**Comment by dyanmei** [comment]
I can successfully build the mitsuba you provided, but there is no mtsimport. Would you mind to send me a link to download the collada you used? Thanks a lot.

**Comment by yindaz** [comment]
I don't remember specifically about that link. But I am sure that we used everything from their official website, and nothing special was used.

**Comment by dyanmei** [comment]
> I don't remember specifically about that link. But I am sure that we used everything from their official website, and nothing special was used.

The problem is solved. Thanks a lot.
